### PR TITLE
Update codes.nora.gDiceRoller.json

### PR DESCRIPTION
**Pull request by Eonfge**
Update runtime to GNOME 44

### CODE REVIEW

**Comment by Eonfge** [comment]
@bilelmoussaoui This is hardly the most relevant package, but since there are still a few people that download it every day, it might be best to update. The runtime is quite ancient, so best to just bump it up a bit.

**Comment by hfiguiere** [comment]
I hadn't done it back then because https://github.com/flathub/codes.nora.gDiceRoller/issues/3#issuecomment-817139758

**Comment by Eonfge** [comment]
I tested it a bit, and it worked on my device (Fedora 38, Wayland). Not sure how much testing an application like this needs.

**Comment by hfiguiere** [comment]
this was happening on startup. and I had filed as "broken gtk-rs" since they are old bindings. but it worked here, otherwise I would have stated it actually was broken.

**Pull request merged**
